SELECT * FROM STYLE
WHERE 1=1
AND ST_GENDER='M';

SELECT * FROM STYLE
WHERE 1=1
AND ST_GENDER='F';

CREATE SEQUENCE STYLE_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  
  NOCYCLE
  NOCACHE
  NOORDER;
  
--여자 스타일
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '러블리');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '섹시');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '모던시크');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '페미닌');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '럭셔리·명품');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '심플베이직');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '유니크');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '10대쇼핑몰');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '미시스타일');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '빅사이즈');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '란제리·언더웨어'); 
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '슈즈'); 
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '가방'); 
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '액세서리·잡화');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'F', '커플룩·비치룩');

--남자 스타일
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'M', '트랜드');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'M', '레플·자작제작');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'M', '유니크·빈티지');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'M', '옴므·클래식·수트');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'M', '빅사이즈');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'M', '슈즈');
INSERT INTO STYLE
VALUES(STYLE_SEQ.NEXTVAL, 'M', '액세서리·잡화');

  