DROP INDEX PK_MEMBER;

DROP INDEX PK_SHOP;

DROP INDEX PK_QNA;

DROP INDEX PK_FREEBOARD;

DROP INDEX PK_PAYMENT;

DROP INDEX PK_REPLY;

DROP INDEX PK_CHIEF;

DROP INDEX PK_STYLE;

DROP INDEX PK_ITEM_TYPE;

DROP INDEX PK_ITEM;

/* 회원 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 쇼핑몰 */
DROP TABLE SHOP 
	CASCADE CONSTRAINTS;

/* 문의 */
DROP TABLE QNA 
	CASCADE CONSTRAINTS;

/* 자유게시판 */
DROP TABLE FREEBOARD 
	CASCADE CONSTRAINTS;

/* 결제 */
DROP TABLE PAYMENT 
	CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE REPLY 
	CASCADE CONSTRAINTS;

/* 사업자 */
DROP TABLE CHIEF 
	CASCADE CONSTRAINTS;

/* 스타일 */
DROP TABLE STYLE 
	CASCADE CONSTRAINTS;

/* 상품종류 */
DROP TABLE ITEM_TYPE 
	CASCADE CONSTRAINTS;

/* 상품 */
DROP TABLE ITEM 
	CASCADE CONSTRAINTS;

/* 회원 */
CREATE TABLE MEMBER (
	M_NO NUMBER NOT NULL, /* 회원번호 */
	M_TYPE VARCHAR2(10) DEFAULT '1' NOT NULL, /* 회원구분값 */
	M_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
	M_NICK VARCHAR2(100) NOT NULL, /* 닉네임 */
	M_PWD VARCHAR2(100) NOT NULL, /* 비밀번호 */
	M_IMAGE VARCHAR2(200), /* 회원이미지 */
	M_REGDATE DATE DEFAULT sysdate NOT NULL, /* 회원등록일 */
	M_CHGDATE DATE /* 회원수정일 */
);

COMMENT ON TABLE MEMBER IS '회원';

COMMENT ON COLUMN MEMBER.M_NO IS '회원번호';

COMMENT ON COLUMN MEMBER.M_TYPE IS '회원구분값';

COMMENT ON COLUMN MEMBER.M_EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.M_NICK IS '닉네임';

COMMENT ON COLUMN MEMBER.M_PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.M_IMAGE IS '회원이미지';

COMMENT ON COLUMN MEMBER.M_REGDATE IS '회원등록일';

COMMENT ON COLUMN MEMBER.M_CHGDATE IS '회원수정일';

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		M_NO ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			M_NO
		);

/* 쇼핑몰 */
CREATE TABLE SHOP (
	S_NO NUMBER NOT NULL, /* 쇼핑몰관리번호 */
	S_DOMAIN VARCHAR2(200) NOT NULL, /* 쇼핑몰도메인 */
	S_MSYN VARCHAR2(10) DEFAULT 'N' NOT NULL, /* 모바일사이트유무 */
	S_NAME VARCHAR2(200) NOT NULL, /* 쇼핑몰명 */
	S_BIMAGE VARCHAR2(200), /* 쇼핑몰큰이미지 */
	S_SIMAGE VARCHAR2(200), /* 쇼핑몰작은이미지 */
	S_BINFO CLOB, /* 쇼핑몰큰설명 */
	S_SINFO CLOB, /* 쇼핑몰작은설명 */
	S_AGE VARCHAR2(10) NOT NULL, /* 쇼핑몰연령대구분값 */
	ST_NO NUMBER, /* 스타일번호 */
	ST_GENDER VARCHAR2(10), /* 스타일성별 */
	S_STAFF VARCHAR2(200) NOT NULL, /* 담당자명 */
	S_DEP VARCHAR2(200), /* 부서명 */
	S_POSITION VARCHAR2(200), /* 직급 */
	S_TEL VARCHAR2(200), /* 담당자전화번호 */
	S_PHONE VARCHAR2(200), /* 담당자휴대폰 */
	S_EMAIL VARCHAR2(200), /* 담당자이메일 */
	S_HIT NUMBER DEFAULT 0 NOT NULL, /* 조회수 */
	S_ACCYN VARCHAR2(10) DEFAULT 'N' NOT NULL, /* 광고신청유무 */
	S_ACCDATE DATE, /* 광고신청일 */
	S_PAYYN VARCHAR2(10) DEFAULT 'N' NOT NULL, /* 결제확인유무 */
	S_REGDATE DATE DEFAULT SYSDATE NOT NULL, /* 쇼핑몰등록일 */
	S_CHGDATE DATE, /* 쇼핑몰수정일 */
	C_NO NUMBER NOT NULL /* 사업자등록번호 */
);

COMMENT ON TABLE SHOP IS '쇼핑몰';

COMMENT ON COLUMN SHOP.S_NO IS '쇼핑몰관리번호';

COMMENT ON COLUMN SHOP.S_DOMAIN IS '쇼핑몰도메인';

COMMENT ON COLUMN SHOP.S_MSYN IS '모바일사이트유무';

COMMENT ON COLUMN SHOP.S_NAME IS '쇼핑몰명';

COMMENT ON COLUMN SHOP.S_BIMAGE IS '쇼핑몰큰이미지';

COMMENT ON COLUMN SHOP.S_SIMAGE IS '쇼핑몰작은이미지';

COMMENT ON COLUMN SHOP.S_BINFO IS '쇼핑몰큰설명';

COMMENT ON COLUMN SHOP.S_SINFO IS '쇼핑몰작은설명';

COMMENT ON COLUMN SHOP.S_AGE IS '쇼핑몰연령대구분값';

COMMENT ON COLUMN SHOP.ST_NO IS '스타일번호';

COMMENT ON COLUMN SHOP.ST_GENDER IS '스타일성별';

COMMENT ON COLUMN SHOP.S_STAFF IS '담당자명';

COMMENT ON COLUMN SHOP.S_DEP IS '부서명';

COMMENT ON COLUMN SHOP.S_POSITION IS '직급';

COMMENT ON COLUMN SHOP.S_TEL IS '담당자전화번호';

COMMENT ON COLUMN SHOP.S_PHONE IS '담당자휴대폰';

COMMENT ON COLUMN SHOP.S_EMAIL IS '담당자이메일';

COMMENT ON COLUMN SHOP.S_HIT IS '조회수';

COMMENT ON COLUMN SHOP.S_ACCYN IS '광고신청유무';

COMMENT ON COLUMN SHOP.S_ACCDATE IS '광고신청일';

COMMENT ON COLUMN SHOP.S_PAYYN IS '결제확인유무';

COMMENT ON COLUMN SHOP.S_REGDATE IS '쇼핑몰등록일';

COMMENT ON COLUMN SHOP.S_CHGDATE IS '쇼핑몰수정일';

COMMENT ON COLUMN SHOP.C_NO IS '사업자등록번호';

CREATE UNIQUE INDEX PK_SHOP
	ON SHOP (
		S_NO ASC
	);

ALTER TABLE SHOP
	ADD
		CONSTRAINT PK_SHOP
		PRIMARY KEY (
			S_NO
		);

/* 문의 */
CREATE TABLE QNA (
	Q_NO NUMBER NOT NULL, /* 문의번호 */
	Q_TITLE VARCHAR2(200) NOT NULL, /* 문의제목 */
	Q_CONTENT CLOB NOT NULL, /* 문의내용 */
	Q_EMAIL VARCHAR2(200) NOT NULL, /* 문의이메일 */
	Q_TEL VARCHAR2(200) NOT NULL, /* 문의연락처 */
	Q_REGDATE DATE DEFAULT SYSDATE NOT NULL, /* 문의등록일 */
	M_NO NUMBER NOT NULL /* 회원번호 */
);

COMMENT ON TABLE QNA IS '문의';

COMMENT ON COLUMN QNA.Q_NO IS '문의번호';

COMMENT ON COLUMN QNA.Q_TITLE IS '문의제목';

COMMENT ON COLUMN QNA.Q_CONTENT IS '문의내용';

COMMENT ON COLUMN QNA.Q_EMAIL IS '문의이메일';

COMMENT ON COLUMN QNA.Q_TEL IS '문의연락처';

COMMENT ON COLUMN QNA.Q_REGDATE IS '문의등록일';

COMMENT ON COLUMN QNA.M_NO IS '회원번호';

CREATE UNIQUE INDEX PK_QNA
	ON QNA (
		Q_NO ASC
	);

ALTER TABLE QNA
	ADD
		CONSTRAINT PK_QNA
		PRIMARY KEY (
			Q_NO
		);

/* 자유게시판 */
CREATE TABLE FREEBOARD (
	B_NO NUMBER NOT NULL, /* 글번호 */
	B_TITLE VARCHAR2(200) NOT NULL, /* 글제목 */
	B_CONTENT CLOB NOT NULL, /* 글내용 */
	B_FILENAME VARCHAR2(200), /* 업로드파일명 */
	B_FILESIZE NUMBER, /* 파일크기 */
	B_ORIGINALFILENAME VARCHAR2(200), /* 파일명 */
	B_REGDATE DATE DEFAULT SYSDATE NOT NULL, /* 글등록일 */
	B_CHGDATE DATE, /* 글수정일 */
	B_READCOUNT NUMBER DEFAULT 1 NOT NULL, /* 조회수 */
	M_NO NUMBER NOT NULL /* 회원번호 */
);

COMMENT ON TABLE FREEBOARD IS '자유게시판';

COMMENT ON COLUMN FREEBOARD.B_NO IS '글번호';

COMMENT ON COLUMN FREEBOARD.B_TITLE IS '글제목';

COMMENT ON COLUMN FREEBOARD.B_CONTENT IS '글내용';

COMMENT ON COLUMN FREEBOARD.B_FILENAME IS '업로드파일명';

COMMENT ON COLUMN FREEBOARD.B_FILESIZE IS '파일크기';

COMMENT ON COLUMN FREEBOARD.B_ORIGINALFILENAME IS '파일명';

COMMENT ON COLUMN FREEBOARD.B_REGDATE IS '글등록일';

COMMENT ON COLUMN FREEBOARD.B_CHGDATE IS '글수정일';

COMMENT ON COLUMN FREEBOARD.B_READCOUNT IS '조회수';

COMMENT ON COLUMN FREEBOARD.M_NO IS '회원번호';

CREATE UNIQUE INDEX PK_FREEBOARD
	ON FREEBOARD (
		B_NO ASC
	);

ALTER TABLE FREEBOARD
	ADD
		CONSTRAINT PK_FREEBOARD
		PRIMARY KEY (
			B_NO
		);

/* 결제 */
CREATE TABLE PAYMENT (
	P_NO NUMBER NOT NULL, /* 광고등록번호 */
	P_YEAR VARCHAR2(4) NOT NULL, /* 결제년도 */
	P_MONTH VARCHAR2(2) NOT NULL, /* 결제월 */
	P_DAY VARCHAR2(8) NOT NULL, /* 결제년월일 */
	P_REGDATE DATE NOT NULL, /* 광고등록일 */
	P_EXTDATE DATE NOT NULL, /* 광고만료일 */
	S_NO NUMBER NOT NULL /* 쇼핑몰관리번호 */
);

COMMENT ON TABLE PAYMENT IS '결제';

COMMENT ON COLUMN PAYMENT.P_NO IS '광고등록번호';

COMMENT ON COLUMN PAYMENT.P_YEAR IS '결제년도';

COMMENT ON COLUMN PAYMENT.P_MONTH IS '결제월';

COMMENT ON COLUMN PAYMENT.P_DAY IS '결제년월일';

COMMENT ON COLUMN PAYMENT.P_REGDATE IS '광고등록일';

COMMENT ON COLUMN PAYMENT.P_EXTDATE IS '광고만료일';

COMMENT ON COLUMN PAYMENT.S_NO IS '쇼핑몰관리번호';

CREATE UNIQUE INDEX PK_PAYMENT
	ON PAYMENT (
		P_NO ASC,
		P_YEAR ASC,
		P_MONTH ASC
	);

ALTER TABLE PAYMENT
	ADD
		CONSTRAINT PK_PAYMENT
		PRIMARY KEY (
			P_NO,
			P_YEAR,
			P_MONTH
		);

/* 댓글 */
CREATE TABLE REPLY (
	R_NO NUMBER NOT NULL, /* 댓글번호 */
	R_NO_GROUP NUMBER NOT NULL, /* 댓글번호구분값 */
	R_GBN NUMBER NOT NULL, /* 댓글구분값 */
	R_CONTENT CLOB NOT NULL, /* 댓글내용 */
	R_REGDATE DATE DEFAULT SYSDATE NOT NULL, /* 댓글등록일 */
	R_CHGDATE DATE, /* 댓글수정일 */
	B_NO NUMBER NOT NULL, /* 글번호 */
	M_NO NUMBER /* 회원번호 */
);

COMMENT ON TABLE REPLY IS '댓글';

COMMENT ON COLUMN REPLY.R_NO IS '댓글번호';

COMMENT ON COLUMN REPLY.R_NO_GROUP IS '댓글번호구분값';

COMMENT ON COLUMN REPLY.R_GBN IS '댓글구분값';

COMMENT ON COLUMN REPLY.R_CONTENT IS '댓글내용';

COMMENT ON COLUMN REPLY.R_REGDATE IS '댓글등록일';

COMMENT ON COLUMN REPLY.R_CHGDATE IS '댓글수정일';

COMMENT ON COLUMN REPLY.B_NO IS '글번호';

COMMENT ON COLUMN REPLY.M_NO IS '회원번호';

CREATE UNIQUE INDEX PK_REPLY
	ON REPLY (
		R_NO ASC
	);

ALTER TABLE REPLY
	ADD
		CONSTRAINT PK_REPLY
		PRIMARY KEY (
			R_NO
		);

/* 사업자 */
CREATE TABLE CHIEF (
	C_NO NUMBER NOT NULL, /* 사업자등록번호 */
	C_NUMBER VARCHAR2(100) NOT NULL, /* 사업자번호 */
	C_EMAIL VARCHAR2(100), /* 사업자이메일 */
	C_PWD VARCHAR2(100), /* 사업자비밀번호 */
	C_NAME VARCHAR2(100), /* 사업자명 */
	C_CNAME VARCHAR2(200), /* 사업장명 */
	C_ADD VARCHAR2(200), /* 사업장주소 */
	C_REGDATE DATE DEFAULT SYSDATE NOT NULL, /* 사업자등록일 */
	C_CHGDATE DATE, /* 사업자수정일 */
	C_TYPE VARCHAR2(10) DEFAULT 1 NOT NULL /* 사업자구분값 */
);

COMMENT ON TABLE CHIEF IS '사업자';

COMMENT ON COLUMN CHIEF.C_NO IS '사업자등록번호';

COMMENT ON COLUMN CHIEF.C_NUMBER IS '사업자번호';

COMMENT ON COLUMN CHIEF.C_EMAIL IS '사업자이메일';

COMMENT ON COLUMN CHIEF.C_PWD IS '사업자비밀번호';

COMMENT ON COLUMN CHIEF.C_NAME IS '사업자명';

COMMENT ON COLUMN CHIEF.C_CNAME IS '사업장명';

COMMENT ON COLUMN CHIEF.C_ADD IS '사업장주소';

COMMENT ON COLUMN CHIEF.C_REGDATE IS '사업자등록일';

COMMENT ON COLUMN CHIEF.C_CHGDATE IS '사업자수정일';

COMMENT ON COLUMN CHIEF.C_TYPE IS '사업자구분값';

CREATE UNIQUE INDEX PK_CHIEF
	ON CHIEF (
		C_NO ASC
	);

ALTER TABLE CHIEF
	ADD
		CONSTRAINT PK_CHIEF
		PRIMARY KEY (
			C_NO
		);

/* 스타일 */
CREATE TABLE STYLE (
	ST_NO NUMBER NOT NULL, /* 스타일번호 */
	ST_GENDER VARCHAR2(10) NOT NULL, /* 스타일성별 */
	ST_NAME VARCHAR2(200) NOT NULL /* 스타일이름 */
);

COMMENT ON TABLE STYLE IS '스타일';

COMMENT ON COLUMN STYLE.ST_NO IS '스타일번호';

COMMENT ON COLUMN STYLE.ST_GENDER IS '스타일성별';

COMMENT ON COLUMN STYLE.ST_NAME IS '스타일이름';

CREATE UNIQUE INDEX PK_STYLE
	ON STYLE (
		ST_NO ASC,
		ST_GENDER ASC
	);

ALTER TABLE STYLE
	ADD
		CONSTRAINT PK_STYLE
		PRIMARY KEY (
			ST_NO,
			ST_GENDER
		);

/* 상품종류 */
CREATE TABLE ITEM_TYPE (
	IT_NO NUMBER NOT NULL, /* 상품종류번호 */
	IT_NAME VARCHAR2(200) NOT NULL, /* 상품종류이름 */
	IT_GENDER VARCHAR2(10) /* 상품성별 */
);

COMMENT ON TABLE ITEM_TYPE IS '상품종류';

COMMENT ON COLUMN ITEM_TYPE.IT_NO IS '상품종류번호';

COMMENT ON COLUMN ITEM_TYPE.IT_NAME IS '상품종류이름';

COMMENT ON COLUMN ITEM_TYPE.IT_GENDER IS '상품성별';

CREATE UNIQUE INDEX PK_ITEM_TYPE
	ON ITEM_TYPE (
		IT_NO ASC
	);

ALTER TABLE ITEM_TYPE
	ADD
		CONSTRAINT PK_ITEM_TYPE
		PRIMARY KEY (
			IT_NO
		);

/* 상품 */
CREATE TABLE ITEM (
	I_NO NUMBER NOT NULL, /* 상품번호 */
	I_NAME VARCHAR2(200) NOT NULL, /* 상품이름 */
	I_IMAGE VARCHAR2(200) NOT NULL, /* 상품이미지 */
	I_REGDATE DATE DEFAULT sysdate NOT NULL, /* 상품등록일 */
	I_CHGDATE DATE, /* 상품수정일 */
	IT_NO NUMBER, /* 상품종류번호 */
	S_NO NUMBER /* 쇼핑몰관리번호 */
);

COMMENT ON TABLE ITEM IS '상품';

COMMENT ON COLUMN ITEM.I_NO IS '상품번호';

COMMENT ON COLUMN ITEM.I_NAME IS '상품이름';

COMMENT ON COLUMN ITEM.I_IMAGE IS '상품이미지';

COMMENT ON COLUMN ITEM.I_REGDATE IS '상품등록일';

COMMENT ON COLUMN ITEM.I_CHGDATE IS '상품수정일';

COMMENT ON COLUMN ITEM.IT_NO IS '상품종류번호';

COMMENT ON COLUMN ITEM.S_NO IS '쇼핑몰관리번호';

CREATE UNIQUE INDEX PK_ITEM
	ON ITEM (
		I_NO ASC
	);

ALTER TABLE ITEM
	ADD
		CONSTRAINT PK_ITEM
		PRIMARY KEY (
			I_NO
		);

ALTER TABLE SHOP
	ADD
		CONSTRAINT FK_CHIEF_TO_SHOP
		FOREIGN KEY (
			C_NO
		)
		REFERENCES CHIEF (
			C_NO
		);

ALTER TABLE SHOP
	ADD
		CONSTRAINT FK_STYLE_TO_SHOP
		FOREIGN KEY (
			ST_NO,
			ST_GENDER
		)
		REFERENCES STYLE (
			ST_NO,
			ST_GENDER
		);

ALTER TABLE QNA
	ADD
		CONSTRAINT FK_MEMBER_TO_QNA
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);

ALTER TABLE FREEBOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_FREEBOARD
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);

ALTER TABLE PAYMENT
	ADD
		CONSTRAINT FK_SHOP_TO_PAYMENT
		FOREIGN KEY (
			S_NO
		)
		REFERENCES SHOP (
			S_NO
		);

ALTER TABLE REPLY
	ADD
		CONSTRAINT FK_FREEBOARD_TO_REPLY
		FOREIGN KEY (
			B_NO
		)
		REFERENCES FREEBOARD (
			B_NO
		);

ALTER TABLE REPLY
	ADD
		CONSTRAINT FK_MEMBER_TO_REPLY
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);

ALTER TABLE ITEM
	ADD
		CONSTRAINT FK_ITEM_TYPE_TO_ITEM
		FOREIGN KEY (
			IT_NO
		)
		REFERENCES ITEM_TYPE (
			IT_NO
		);

ALTER TABLE ITEM
	ADD
		CONSTRAINT FK_SHOP_TO_ITEM
		FOREIGN KEY (
			S_NO
		)
		REFERENCES SHOP (
			S_NO
		);